### ISSUE TITLE
i need help 

### ISSUE THREAD

**Issue by essamgoda** [bryan-emmanuel/sonet#2]
when i import this project it show this msg :
" Error:(33, 0) Could not find property 'twitter.key' on root project 'sonet-master'. "

**Comment by piusvelte** [comment]
The keys are private. To build and use Sonet yourself, you would need to register developer accounts for any network (twitter, etc.) that you want to use, and put the OAuth token/secret in a file called "gradle.properties" in the root of the project. For twitter, the file could contain something like the following:
twitter.key=YourUniqueKey
twitter.secret=YourUniqueSecret
